# Generated by Django 3.0.8 on 2020-07-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaseWord', models.CharField(max_length=255)),
                ('Defn', models.TextField()),
                ('CEFR', models.CharField(max_length=255)),
                ('Guideword', models.CharField(max_length=255)),
                ('Level', models.TextField()),
                ('PartOfSpeech', models.CharField(max_length=255)),
                ('EngDefn', models.TextField()),
                ('Pron', models.TextField()),
                ('Audio', models.TextField()),
                ('Comments', models.TextField()),
                ('Type', models.CharField(max_length=255)),
                ('Topic', models.CharField(max_length=255)),
                ('Grammar', models.CharField(max_length=255)),
            ],
        ),
    ]
