# Generated by Django 3.0.8 on 2020-07-22 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocabexam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='static/avatar/')),
                ('invitecode', models.CharField(blank=True, max_length=127)),
                ('wechat_openid', models.TextField(blank=True)),
                ('wechat_unionid', models.TextField(blank=True)),
                ('nickname', models.CharField(blank=True, max_length=127)),
                ('gender', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=63)),
                ('dob', models.DateField()),
                ('signature', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
