# Generated by Django 3.0.8 on 2020-07-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabexam', '0003_auto_20200728_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=63),
        ),
    ]
